---
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    environment:
      - TZ=${TZ}
      #- WATCHTOWER_CLEANUP=true #Broken right now using cron prune
      - WATCHTOWER_ROLLING_RESTART=true
      #- WATCHTOWER_DEBUG=true
      - WATCHTOWER_SCHEDULE=* 2 6 * * 5
      #- WATCHTOWER_RUN_ONCE=true
      ## Watchtower autodetects discord urls and uses shoutrr##
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${WATCHTOWER_WEBHOOK_URL}/slack
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=Watchtower
      - WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI=":whale:"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
